# Generated by Django 5.2 on 2025-05-02 05:49

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chatapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='chatmessage',
            name='timestamp',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='chatmessage',
            name='role',
            field=models.CharField(max_length=10),
        ),
        migrations.AlterField(
            model_name='chatmessage',
            name='session_id',
            field=models.CharField(max_length=255),
        ),
    ]
